// Per-trade "tribunal verdict" for the Trade Tribunal page. Like
// power-ranking-blurb and rivalry-blurb, this is a render-time helper that
// returns plain text WITHOUT logging to the DB — cheap and instant with the
// mock provider; a real provider should be pre-generated by the weekly cron
// rather than called per request.

import { getAIProvider } from "../get-ai-provider";
import { buildSystemPrompt } from "../prompt-helpers";
import type { ContentSafeguards } from "../types";

export const TRADE_VERDICT_PROMPT_VERSION = "trade-verdict-v1";

export interface TradeVerdictSide {
  managerName: string;
  /** Human-readable list of what this side acquired, e.g. ["Josh Allen (QB)"]. */
  acquired: string[];
}

export interface TradeVerdictInput {
  seasonYear: number;
  /** Week the trade processed; null when unknown. */
  week: number | null;
  sides: TradeVerdictSide[];
  /**
   * Plain-language hindsight result, e.g.
   * "Alice's haul outscored Bob's by 45.3 points rest-of-season" or,
   * when player scoring is missing, "insufficient evidence".
   */
  hindsightSummary: string;
  /** False when the season has no player-level scoring to judge by. */
  hindsightAvailable: boolean;
}

const SYSTEM_PROMPT = `You are the staff writer for "The Rat Trap", a fantasy football league's own newspaper, presiding over the "Trade Tribunal". Given a completed trade and the rest-of-season hindsight on who got the better haul, deliver a judgmental, funny "tribunal verdict" of ONE to THREE sentences — decide who won the trade and needle the loser. When the evidence is insufficient (no player-level scoring for that era), say the tribunal cannot rule and keep it short and light. Plain prose, no JSON, no preamble, no headings.`;

export async function generateTradeVerdict(
  input: TradeVerdictInput,
  safeguards: ContentSafeguards,
): Promise<string> {
  const systemPrompt = buildSystemPrompt(SYSTEM_PROMPT, safeguards);

  const when = input.week != null ? `Week ${input.week}, ${input.seasonYear}` : `${input.seasonYear} season`;
  const sideLines = input.sides.map(
    (s) => `${s.managerName} acquired: ${s.acquired.length ? s.acquired.join(", ") : "nothing of note"}.`,
  );

  const userPrompt = [
    `Trade processed ${when}.`,
    ...sideLines,
    input.hindsightAvailable
      ? `Hindsight (rest-of-season production): ${input.hindsightSummary}.`
      : `Hindsight: insufficient evidence — the tribunal lacks player-level scoring for this era, so no numbers exist to judge the haul.`,
  ].join("\n");

  const result = await getAIProvider().generate({
    promptVersion: TRADE_VERDICT_PROMPT_VERSION,
    systemPrompt,
    userPrompt,
    humorLevel: safeguards.humorLevel,
    maxOutputTokens: 120,
  });
  return result.text.trim();
}
